# To find available font names on your system, open Kitty and run:
# kitty +list-fonts --psnames
# Look for names that end in "Nerd Font" or "NF".
# You can specify different fonts for bold, italic, and bold-italic variants.
# 'auto' lets Kitty try to figure it out from the main font family, which usually works well.
bold_font        auto
italic_font      auto
bold_italic_font auto
font:
  normal:
    family: "FiraCode Nerd Font"
  size: 13.0

# The font size in points.
font_size        16.0

# Foreground (text) color
foreground            #D8DEE9
# Background color
background            #2E3440

# Cursor color
cursor                #88C0D0
cursor_text_color     #2E3440

# Black (and bright black)
color0                #3B4252
color8                #4C566A

# Red (and bright red)
color1                #BF616A
color9                #BF616A
background_opacity    0.9
# Dim inactive windows
dim_inactive_windows  yes
dim_opacity           0.75

# Sounds and notifications
enable_audio_bell no

# Increase/decrease font size
map ctrl+plus    change_font_size all +2.0
map ctrl+minus   change_font_size all -2.0
map ctrl+backspace change_font_size all 0

# New tab, close tab, next/previous tab
map ctrl+shift+enter launch --cwd=current
map ctrl+shift+t launch --type=tab --cwd=current
map ctrl+shift+q close_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
 
# ===  Window Navigation (Vim-style)  === #
map alt+h        neighboring_window left
map alt+j        neighboring_window down
map alt+k        neighboring_window up
map alt+l        neighboring_window right




font_family      FiraCode Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

symbol_map U+E000-U+F8FF Symbols Nerd Font
symbol_map U+1F000-U+1FFFF Noto Color Emoji

