#!bin/bash
source ~/py/bin/activate

alias paraguarda='~/.programmi/ParaView-5.13.0-MPI-Linux-Python3.10-x86_64/bin/paraview'
alias balena='~/.programmi/balenaEtcher-linux-x64/balena-etcher'
alias nvim='~/.programmi/neovim/bin/nvim'

MEMOCOMUNE=nvme0n1p10
# p5 prima
MONTA=~/Sharedssd

alias monta='sudo mount /dev/$MEMOCOMUNE $MONTA  && systemctl daemon-reload'

alias la='ls -la'
alias ll='ls -ll'

alias DORMI='systemctl poweroff'
alias bloccati='cmatrix -L'

alias ..='cd ..'

alias apri='xdg-open'

alias vvv='nvim ~/ricorda.md'

alias v='nvim'

ciao() {
  fortune | cowsay | lolcat
  sudo mount /dev/$MEMOCOMUNE $MONTA
  sed -n '/# LAVORO DA FARE/,/# MATERIE/{/# MATERIE/!p}' ricorda.md
}

# SOURCE OPENFOAM
source ~/OpenFOAM/OpenFOAM-12/etc/bashrc

# mk.
export mkPrefix=/u/sw/
source ${mkPrefix}/etc/profile
module load gcc-glibc
alias LOAD_MODULES='cd /home/matteo/Sharedssd/università/5AnnoAer/pacs/pacs-examples && source load_modules.sh'

# module load package_name

alias matlab24a='/home/matteodeb/.programmi/MATLAB/bin/matlab &'
alias untarra='tar zxvf'
alias tarr='tar zcvf'
alias UNI='cd ~/Sharedssd/università/5AnnoAer'
alias CTTP='cd ~/OpenFOAM/matteodeb-12/run/CTTP'
alias MAKELATEX='latexmk -pdf main.tex -outdir=build/'


# starship
export starship=/usr/local/bin
alias starship='/usr/local/bin/starship'
eval "$(starship init bash)"
