#!/bin/bash 
shopt -s expand_aliases
alias nvim='~/.programmi/neovim/bin/nvim'

MEMOCOMUNE=/dev/nvme0n1p10
# p5 prima
MONTA=~/Sharedssd


# Shortcuts
alias clc='clear'
alias la='ls -la'
alias ll='ls -ll'
alias bloccati='cmatrix -L'
alias ..='cd ..'
alias apri='xdg-open'
alias vvv='nvim ~/ricorda.md'
alias untarra='tar zxvf'
alias tarr='tar zcvf'
alias v='nvim'
alias codellama='ollama run codellama:13b'


# SOURCE OPENFOAM
alias of12='source ~/OpenFOAM/OpenFOAM-12/etc/bashrc'

# Source python
alias PYTHON='source ~/py/bin/activate'

# mk.
export mkPrefix=/u/sw/

# Functions
# module load package_name
LOAD_MODULES() {
    source ${mkPrefix}/etc/profile
    module load gcc-glibc
    module load fftw
    module load boost
    cd /home/matteo/Sharedssd/università/5AnnoAer/pacs/pacs-examples 
    source load_modules.sh
    cd - > /dev/null
} 

alias UNI='cd ~/Sharedssd/università/5AnnoAer'
alias PACSLABS='UNI && cd pacs/pacs-Labs/Labs/2025/'
alias MAKELATEX='latexmk -pdf main.tex -outdir=build/'

CTTP () { 
    UNI
    cd cttp
    apri teoria.pdf  || echo "Non son riuscito ad aprire il file di teoria"
    apri books/computationalMethodsForFluidDynamics.pdf || echo "Non apro il libro."
}

# starship for cool CLI
export starship=/usr/local/bin
alias starship='/usr/local/bin/starship'
eval "$(starship init bash)"

expand_swap(){
sudo fallocate -l 16G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
}


alias monta='sudo mount "$MEMOCOMUNE" "$MONTA" && systemctl daemon-reload && echo "Memoria montata."'

# Start terminal
ciao() {
    local qui=$PWD 
    if ! mountpoint -q "$MONTA"; then
        monta
    else
        echo "Memo già montata."
    fi
    LOAD_MODULES
    cd ${qui}  > /dev/null || echo "Non riesco a tornare ${qui}"
    PYTHON
    echo "Moduli caricati, py-venv anche."
}

ciao
